### ISSUE TITLE
SSHException: Incompatible ssh peer (no acceptable host key)

### ISSUE THREAD

**Issue by Ezak91** [ploxiln/paramiko-ng#69]
Hey, 

i need to connect to an (specific ssh server on a very specific host).
But i get the Error:

`SSHException: Incompatible ssh peer (no acceptable host key)`

I used your fork because there is no passwort at the beginning its an interactive password later. 
This is my python code:

```
import logging
import paramiko

logging.basicConfig()
logging.getLogger("paramiko").setLevel(logging.DEBUG) # for example

client = paramiko.SSHClient()
client.set_missing_host_key_policy(paramiko.MissingHostKeyPolicy())
client.connect('xx.xxx.xxx.xxx', username='safeguarduser')
```

this is the python error log:

```DEBUG:paramiko.transport:starting thread (client mode): 0x428d6820
DEBUG:paramiko.transport:Local version/idstring: SSH-2.0-paramiko_2.8.0
DEBUG:paramiko.transport:Remote version/idstring: SSH-2.0-1.37g sshlib: T9999H06_14MAY2018_comForte_SSH2_0105a:\TXXXXX.$SSH01
INFO:paramiko.transport:Connected (version 2.0, client 1.37g)
DEBUG:paramiko.transport:kex follows? False
kex algos: ['diffie-hellman-group-exchange-sha256', 'diffie-hellman-group-exchange-sha1', 'diffie-hellman-group14-sha1', 'diffie-hellman-group1-sha1']
server key: ['ssh-dss']
client encrypt: ['aes256-cbc', 'twofish256-cbc', 'twofish-cbc', 'aes128-cbc', 'twofish128-cbc', 'blowfish-cbc', '3des-cbc', 'arcfour', 'cast128-cbc', 'aes256-ctr', 'twofish256-ctr', 'twofish-ctr', 'aes128-ctr', 'twofish128-ctr', 'blowfish-ctr', '3des-ctr', 'cast128-ctr']
server encrypt: ['aes256-cbc', 'twofish256-cbc', 'twofish-cbc', 'aes128-cbc', 'twofish128-cbc', 'blowfish-cbc', '3des-cbc', 'arcfour', 'cast128-cbc', 'aes256-ctr', 'twofish256-ctr', 'twofish-ctr', 'aes128-ctr', 'twofish128-ctr', 'blowfish-ctr', '3des-ctr', 'cast128-ctr']
client mac: ['hmac-sha2-256', 'hmac-sha2-512', 'hmac-sha1', 'hmac-md5', 'hmac-sha1-96', 'hmac-md5-96']
server mac: ['hmac-sha2-256', 'hmac-sha2-512', 'hmac-sha1', 'hmac-md5', 'hmac-sha1-96', 'hmac-md5-96']
client lang: b''
server lang: b''
client compress: ['none', 'zlib']
server compress: ['none', 'zlib']
DEBUG:paramiko.transport:Kex agreed: diffie-hellman-group-exchange-sha256
ERROR:paramiko.transport:Exception: Incompatible ssh peer (no acceptable host key)
ERROR:paramiko.transport:Traceback (most recent call last):
ERROR:paramiko.transport:  File "C:\Users\user\Desktop\python_ssh\.venv\lib\site-packages\paramiko\transport.py", line 1939, in run
ERROR:paramiko.transport:    self._handler_table[ptype](self, m)
ERROR:paramiko.transport:  File "C:\Users\user\Desktop\python_ssh\.venv\lib\site-packages\paramiko\transport.py", line 2040, in _negotiate_keys
ERROR:paramiko.transport:    self._parse_kex_init(m)
ERROR:paramiko.transport:  File "C:\Users\user\Desktop\python_ssh\.venv\lib\site-packages\paramiko\transport.py", line 2213, in _parse_kex_init
ERROR:paramiko.transport:    raise SSHException('Incompatible ssh peer (no acceptable host key)')
ERROR:paramiko.transport:paramiko.ssh_exception.SSHException: Incompatible ssh peer (no acceptable host key)
ERROR:paramiko.transport:
Traceback (most recent call last):
  File "c:/Users/user/Desktop/python_ssh/python_ssh.py", line 9, in <module>
    client.connect('xx.xxx.xxx.xxx', username='safeguarduser')
  File "C:\Users\user\Desktop\python_ssh\.venv\lib\site-packages\paramiko\client.py", line 339, in connect
    t.start_client(timeout=timeout)
  File "C:\Users\user\Desktop\python_ssh\.venv\lib\site-packages\paramiko\transport.py", line 549, in start_client
    raise e
  File "C:\Users\user\Desktop\python_ssh\.venv\lib\site-packages\paramiko\transport.py", line 1939, in run
    self._handler_table[ptype](self, m)
  File "C:\Users\user\Desktop\python_ssh\.venv\lib\site-packages\paramiko\transport.py", line 2040, in _negotiate_keys
    self._parse_kex_init(m)
  File "C:\Users\user\Desktop\python_ssh\.venv\lib\site-packages\paramiko\transport.py", line 2213, in _parse_kex_init
    raise SSHException('Incompatible ssh peer (no acceptable host key)')
paramiko.ssh_exception.SSHException: Incompatible ssh peer (no acceptable host key)
```

and this is a log of a working connection over a shell with the command

`ssh -vvvv -t -o HostKeyAlgorithms=+ssh-dss safeguarduser@xx.xxx.xxx.xxx tacl`

```
debug3: Failed to open file:C:/Users/user/.ssh/config error:2
debug3: Failed to open file:C:/ProgramData/ssh/ssh_config error:2
debug2: resolve_canonicalize: hostname xx.xxx.xxx.xxx is address
debug2: ssh_connect_direct: needpriv 0
debug1: Connecting to xx.xxx.xxx.xxx [xx.xxx.xxx.xxx] port 22.
debug1: Connection established.
debug3: Failed to open file:C:/Users/user/.ssh/id_rsa error:2
debug3: Failed to open file:C:/Users/user/.ssh/id_rsa.pub error:2
debug1: key_load_public: No such file or directory
debug1: identity file C:\\Users\\user/.ssh/id_rsa type -1
debug3: Failed to open file:C:/Users/user/.ssh/id_rsa-cert error:2
debug3: Failed to open file:C:/Users/user/.ssh/id_rsa-cert.pub error:2
debug1: key_load_public: No such file or directory
debug1: identity file C:\\Users\\user/.ssh/id_rsa-cert type -1
debug3: Failed to open file:C:/Users/user/.ssh/id_dsa error:2
debug3: Failed to open file:C:/Users/user/.ssh/id_dsa.pub error:2
debug1: key_load_public: No such file or directory
debug1: identity file C:\\Users\\user/.ssh/id_dsa type -1
debug3: Failed to open file:C:/Users/user/.ssh/id_dsa-cert error:2
debug3: Failed to open file:C:/Users/user/.ssh/id_dsa-cert.pub error:2
debug1: key_load_public: No such file or directory
debug1: identity file C:\\Users\\user/.ssh/id_dsa-cert type -1
debug3: Failed to open file:C:/Users/user/.ssh/id_ecdsa error:2
debug3: Failed to open file:C:/Users/user/.ssh/id_ecdsa.pub error:2
debug1: key_load_public: No such file or directory
debug1: identity file C:\\Users\\user/.ssh/id_ecdsa type -1
debug3: Failed to open file:C:/Users/user/.ssh/id_ecdsa-cert error:2
debug3: Failed to open file:C:/Users/user/.ssh/id_ecdsa-cert.pub error:2
debug1: key_load_public: No such file or directory
debug1: identity file C:\\Users\\user/.ssh/id_ecdsa-cert type -1
debug3: Failed to open file:C:/Users/user/.ssh/id_ed25519 error:2
debug3: Failed to open file:C:/Users/user/.ssh/id_ed25519.pub error:2
debug1: key_load_public: No such file or directory
debug1: identity file C:\\Users\\user/.ssh/id_ed25519 type -1
debug3: Failed to open file:C:/Users/user/.ssh/id_ed25519-cert error:2
debug3: Failed to open file:C:/Users/user/.ssh/id_ed25519-cert.pub error:2
debug1: key_load_public: No such file or directory
debug1: identity file C:\\Users\\user/.ssh/id_ed25519-cert type -1
debug3: Failed to open file:C:/Users/user/.ssh/id_xmss error:2
debug3: Failed to open file:C:/Users/user/.ssh/id_xmss.pub error:2
debug1: key_load_public: No such file or directory
debug1: identity file C:\\Users\\user/.ssh/id_xmss type -1
debug3: Failed to open file:C:/Users/user/.ssh/id_xmss-cert error:2
debug3: Failed to open file:C:/Users/user/.ssh/id_xmss-cert.pub error:2
debug1: key_load_public: No such file or directory
debug1: identity file C:\\Users\\user/.ssh/id_xmss-cert type -1
debug1: Local version string SSH-2.0-OpenSSH_for_Windows_7.7
debug1: Remote protocol version 2.0, remote software version 1.37g sshlib: 
T9999H06_14MAY2018_comForte_SSH2_0105a:\\T05035.$SSH01
debug1: no match: 1.37g sshlib: T9999H06_14MAY2018_comForte_SSH2_0105a:\\T05035.$SSH01
debug2: fd 3 setting O_NONBLOCK
debug1: Authenticating to xx.xxx.xxx.xxx:22 as 'safeguarduser'
debug3: send packet: type 20
debug1: SSH2_MSG_KEXINIT sent
debug3: receive packet: type 20
debug1: SSH2_MSG_KEXINIT received
debug2: local client KEXINIT proposal
debug2: KEX algorithms: curve25519-sha256,curve25519-sha256@libssh.org,ecdh-sha2-nistp256,ecdh-sha2-nistp384,ecdh-sha2-
nistp521,diffie-hellman-group-exchange-sha256,diffie-hellman-group16-sha512,diffie-hellman-group18-sha512,diffie-hellma
n-group-exchange-sha1,diffie-hellman-group14-sha256,diffie-hellman-group14-sha1,ext-info-c
debug2: host key algorithms: ecdsa-sha2-nistp256-cert-v01@openssh.com,ecdsa-sha2-nistp384-cert-v01@openssh.com,ecdsa-sh
a2-nistp521-cert-v01@openssh.com,ssh-ed25519-cert-v01@openssh.com,ssh-rsa-cert-v01@openssh.com,ecdsa-sha2-nistp256,ecds
a-sha2-nistp384,ecdsa-sha2-nistp521,ssh-ed25519,rsa-sha2-512,rsa-sha2-256,ssh-rsa,ssh-dss
debug2: ciphers ctos: 
chacha20-poly1305@openssh.com,aes128-ctr,aes192-ctr,aes256-ctr,aes128-gcm@openssh.com,aes256-gcm@openssh.com
debug2: ciphers stoc: 
chacha20-poly1305@openssh.com,aes128-ctr,aes192-ctr,aes256-ctr,aes128-gcm@openssh.com,aes256-gcm@openssh.com
debug2: MACs ctos: umac-64-etm@openssh.com,umac-128-etm@openssh.com,hmac-sha2-256-etm@openssh.com,hmac-sha2-512-etm@ope
nssh.com,hmac-sha1-etm@openssh.com,umac-64@openssh.com,umac-128@openssh.com,hmac-sha2-256,hmac-sha2-512,hmac-sha1
debug2: MACs stoc: umac-64-etm@openssh.com,umac-128-etm@openssh.com,hmac-sha2-256-etm@openssh.com,hmac-sha2-512-etm@ope
nssh.com,hmac-sha1-etm@openssh.com,umac-64@openssh.com,umac-128@openssh.com,hmac-sha2-256,hmac-sha2-512,hmac-sha1
debug2: compression ctos: none
debug2: compression stoc: none
debug2: languages ctos: 
debug2: languages stoc: 
debug2: first_kex_follows 0 
debug2: reserved 0 
debug2: peer server KEXINIT proposal
debug2: KEX algorithms: diffie-hellman-group-exchange-sha256,diffie-hellman-group-exchange-sha1,diffie-hellman-group14-
sha1,diffie-hellman-group1-sha1
debug2: host key algorithms: ssh-dss
debug2: ciphers ctos: aes256-cbc,twofish256-cbc,twofish-cbc,aes128-cbc,twofish128-cbc,blowfish-cbc,3des-cbc,arcfour,cas
t128-cbc,aes256-ctr,twofish256-ctr,twofish-ctr,aes128-ctr,twofish128-ctr,blowfish-ctr,3des-ctr,cast128-ctr
debug2: ciphers stoc: aes256-cbc,twofish256-cbc,twofish-cbc,aes128-cbc,twofish128-cbc,blowfish-cbc,3des-cbc,arcfour,cas
t128-cbc,aes256-ctr,twofish256-ctr,twofish-ctr,aes128-ctr,twofish128-ctr,blowfish-ctr,3des-ctr,cast128-ctr
debug2: MACs ctos: hmac-sha2-256,hmac-sha2-512,hmac-sha1,hmac-md5,hmac-sha1-96,hmac-md5-96
debug2: MACs stoc: hmac-sha2-256,hmac-sha2-512,hmac-sha1,hmac-md5,hmac-sha1-96,hmac-md5-96
debug2: compression ctos: none,zlib
debug2: compression stoc: none,zlib
debug2: languages ctos: 
debug2: languages stoc: 
debug2: first_kex_follows 0 
debug2: reserved 0 
debug1: kex: algorithm: diffie-hellman-group-exchange-sha256
debug1: kex: host key algorithm: ssh-dss
debug1: kex: server->client cipher: aes128-ctr MAC: hmac-sha2-256 compression: none
debug1: kex: client->server cipher: aes128-ctr MAC: hmac-sha2-256 compression: none
debug3: send packet: type 34
debug1: SSH2_MSG_KEX_DH_GEX_REQUEST(2048<8192<8192) sent
debug3: receive packet: type 31
debug1: got SSH2_MSG_KEX_DH_GEX_GROUP
debug2: bits set: 1007/2048
debug3: send packet: type 32
debug1: SSH2_MSG_KEX_DH_GEX_INIT sent
debug3: receive packet: type 33
debug1: got SSH2_MSG_KEX_DH_GEX_REPLY
debug1: Server host key: ssh-dss SHA256:xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
debug3: Failed to open file:C:/Users/user/.ssh/known_hosts error:2
debug3: hostkeys_foreach: reading file "C:\\Users\\user/.ssh/known_hosts2"
debug3: record_hostkey: found key type DSA in file C:\\Users\\user/.ssh/known_hosts2:1
debug3: load_hostkeys: loaded 1 keys from xx.xxx.xxx.xxx
debug3: Failed to open file:C:/ProgramData/ssh/ssh_known_hosts error:2
debug3: Failed to open file:C:/ProgramData/ssh/ssh_known_hosts2 error:2
debug1: Host 'xx.xxx.xxx.xxx' is known and matches the DSA host key.
debug1: Found key in C:\\Users\\user/.ssh/known_hosts2:1
debug2: bits set: 1032/2048
debug3: send packet: type 21
debug2: set_newkeys: mode 1
debug1: rekey after 4294967296 blocks
debug1: SSH2_MSG_NEWKEYS sent
debug1: expecting SSH2_MSG_NEWKEYS
debug3: receive packet: type 21
debug1: SSH2_MSG_NEWKEYS received
debug2: set_newkeys: mode 0
debug1: rekey after 4294967296 blocks
debug3: unable to connect to pipe \\\\.\\pipe\\openssh-ssh-agent, error: 2
debug1: pubkey_prepare: ssh_get_authentication_socket: No such file or directory
debug2: key: C:\\Users\\user/.ssh/id_rsa (0000000000000000)
debug2: key: C:\\Users\\user/.ssh/id_dsa (0000000000000000)
debug2: key: C:\\Users\\user/.ssh/id_ecdsa (0000000000000000)
debug2: key: C:\\Users\\user/.ssh/id_ed25519 (0000000000000000)
debug2: key: C:\\Users\\user/.ssh/id_xmss (0000000000000000)
debug3: send packet: type 5
debug3: receive packet: type 6
debug2: service_accept: ssh-userauth
debug1: SSH2_MSG_SERVICE_ACCEPT received
debug3: send packet: type 50
debug3: receive packet: type 52
debug1: Authentication succeeded (none).
Authenticated to xx.xxx.xxx.xxx ([xx.xxx.xxx.xxx]:22).
debug2: fd 6 setting O_NONBLOCK
debug1: channel 0: new [client-session]
debug3: ssh_session2_open: channel_new: 0
debug2: channel 0: send open
debug3: send packet: type 90
debug1: Entering interactive session.
debug1: pledge: network
debug1: console supports the ansi parsing
debug3: Successfully set console output code page from:65001 to 65001
debug3: Successfully set console input code page from:65001 to 65001
debug3: receive packet: type 91
debug2: channel_input_open_confirmation: channel 0: callback start
debug2: fd 3 setting TCP_NODELAY
debug2: client_session2_setup: id 0
debug2: channel 0: request pty-req confirm 1
debug3: send packet: type 98
debug1: Sending command: tacl
debug2: channel 0: request exec confirm 1
debug3: send packet: type 98
debug2: channel_input_open_confirmation: channel 0: callback done
debug2: channel 0: open confirm rwindow 1048576 rmax 57344
debug3: receive packet: type 99
debug2: channel_input_status_confirm: type 99 id 0
debug2: PTY allocation request accepted on channel 0
debug3: receive packet: type 99
debug2: channel_input_status_confirm: type 99 id 0
debug2: exec request accepted on channel 0
```

Hope you can help me

Thank you and best regards

**Comment by ploxiln** [comment]
This is because the server offers only a DSA host key: `server key: ['ssh-dss']` This is an old and these days unusual type.  Support for this kind of key is disabled by default in paramiko-ng.

If you were using the `Transport` class directly, you would use `get_security_options()` and then change the preferred key types. But since you're using `SSHClient`, there is not yet a good way to change those on the transport the client creates. So I suggest trying this hacky work-around (put it just before your code):

```python
paramiko.transport.Transport._preferred_keys += ('ssh-dss',)
```

(that is concatenating a tuple, that extra comma is significant)

**Comment by Ezak91** [comment]
@ploxiln  thank you very much, now i get closer

```
DEBUG:paramiko.transport:HostKey agreed: ssh-dss
DEBUG:paramiko.transport:Cipher agreed: aes128-ctr
DEBUG:paramiko.transport:MAC agreed: hmac-sha2-256
DEBUG:paramiko.transport:Compression agreed: none
DEBUG:paramiko.transport:Got server p (2048 bits)
DEBUG:paramiko.transport:kex engine KexGexSHA256 specified hash_algo <built-in function openssl_sha256>
DEBUG:paramiko.transport:Switch to new keys ...
DEBUG:paramiko.transport:userauth is OK
INFO:paramiko.transport:Authentication (none) successful!
DEBUG:paramiko.transport:[chan 0] Max packet in: 32768 bytes
DEBUG:paramiko.transport:[chan 0] Max packet out: 57344 bytes
DEBUG:paramiko.transport:Secsh channel 0 opened.
DEBUG:paramiko.transport:[chan 0] Sesch channel 0 request ok
DEBUG:paramiko.transport:[chan 0] Sesch channel 0 request ok
DEBUG:paramiko.transport:EOF in transport thread
```

Now i get direct a eof in transport thread after authentication 

i think i need the command for the tacl subshell see tacl and the -t flag for the pty, how can i do this in paramiko? Thank you so much

```
ssh -vvvv -t -o HostKeyAlgorithms=+ssh-dss safeguarduser@xx.xxx.xxx.xxx tacl
```

**Comment by ploxiln** [comment]
That's not as easy unfortunately, see https://github.com/paramiko/paramiko/issues/1304#issuecomment-425597383

**Comment by Ezak91** [comment]
The following is working for me:

```
paramiko.transport.Transport._preferred_keys += ('ssh-dss',)
client = paramiko.SSHClient()
client.set_missing_host_key_policy(paramiko.MissingHostKeyPolicy())
client.connect('xx.xxx.xxx.xx', username='user')
chan = client.get_transport().open_session()
chan.get_pty("xterm")
chan.exec_command('TACL')
buff=''
while not buff.endswith('> '): # Checking for returned prompt
    resp = chan.recv(1024)
    buff += resp.decode()
    print(resp)

chan.send("LOGON group.user\r")

buff=''
while not buff.endswith(': '): # Checking for returned prompt
    resp = chan.recv(1024)
    buff += resp.decode()
    print(resp)
```

Thank you very much for your help
