### ISSUE TITLE
AuthenticationException when connect()'s password attribute is a variable

### ISSUE THREAD

**Issue by ZupoLlask** [ploxiln/paramiko-ng#79]
Hi @ploxiln!

Yesterday I stumbled upon the following weird behavior.

When I pass the password attribute to paramiko.SSHClient().connect() method as a variable (class str type):

**Pseudo-code:**
```
host = '192.168.0.101'
username = 'youruser'
password = 'yourpass'
paramiko.SSHClient().connect(host, username=username, password=password)
```

... and not as direct string:

**Pseudo-code:**
```
host = '192.168.0.101'
username = 'youruser'
paramiko.SSHClient().connect(host, username=username, password='yourpass')
```

... I get the following stack trace:

```
---------------------------------------------------------------------------
AuthenticationException                   Traceback (most recent call last)
<ipython-input-6-7a350efc299d> in <module>
     34     return exit_status
     35 
---> 36 runCommand('192.168.0.101', 'youruser', 'yourpass', 'ls -al')

<ipython-input-6-7a350efc299d> in runCommand(host, username, password, cmd)
     26     client.set_missing_host_key_policy(paramiko.AutoAddPolicy())
     27     #print(f"{host}", f"username={username}", f"{password}")
---> 28     client.connect(f"{host}", username=f"{username}", password=f"{password}")
     29     stdin, stdout, stderr = client.exec_command(f"{cmd}")
     30     for line in stdout:

C:\Anaconda3\lib\site-packages\paramiko\client.py in connect(self, hostname, port, username, password, pkey, key_filename, timeout, allow_agent, look_for_keys, compress, sock, gss_auth, gss_kex, gss_deleg_creds, gss_host, banner_timeout, auth_timeout, gss_trust_dns, passphrase)
    369             username, password, pkey, key_filenames, allow_agent,
    370             look_for_keys, gss_auth, gss_kex, gss_deleg_creds, t.gss_host,
--> 371             passphrase,
    372         )
    373 

C:\Anaconda3\lib\site-packages\paramiko\client.py in _auth(self, username, password, pkey, key_filenames, allow_agent, look_for_keys, gss_auth, gss_kex, gss_deleg_creds, gss_host, passphrase)
    678         # if we got an auth-failed exception earlier, re-raise it
    679         if saved_exception is not None:
--> 680             raise saved_exception
    681         raise SSHException('No authentication methods available')
    682 

C:\Anaconda3\lib\site-packages\paramiko\client.py in _auth(self, username, password, pkey, key_filenames, allow_agent, look_for_keys, gss_auth, gss_kex, gss_deleg_creds, gss_host, passphrase)
    661                 self._log(DEBUG, 'Trying password')
    662                 allowed_types = set(
--> 663                     self._transport.auth_password(username, password))
    664                 two_factor = allowed_types & two_factor_types
    665                 if not two_factor:

C:\Anaconda3\lib\site-packages\paramiko\transport.py in auth_password(self, username, password, event, fallback)
   1385             return []
   1386         try:
-> 1387             return self.auth_handler.wait_for_response(my_event)
   1388         except BadAuthenticationType as e:
   1389             # if password auth isn't allowed, but keyboard-interactive *is*,

C:\Anaconda3\lib\site-packages\paramiko\auth_handler.py in wait_for_response(self, event)
    221             if isinstance(e, PartialAuthentication):
    222                 return e.allowed_types
--> 223             raise e
    224         return []
    225 

AuthenticationException: Authentication failed.
```

When I pass the password attribute the other way, it works as expected.
Do you have any idea of the reason for this behavior?

I'm using v2.8.2 but also tried with the latest upstream version.

Similar cases from upstream:
- https://github.com/paramiko/paramiko/issues/1522
- https://github.com/paramiko/paramiko/issues/1534

**Comment by ploxiln** [comment]
These two code samples are 100% equivalent, there is no possibility of any different behavior between them:

```python
pass = 'yourpass'
paramiko.SSHClient().connect(host, username=user, password=pass)
```

```python
paramiko.SSHClient().connect(host, username=user, password='yourpass')
```

If you see different behavior, then it must be luck of timing, or an accidental typo of username or password in one of the cases.

**Comment by ploxiln** [comment]
... but note that `pass` is a python keyword, not a good choice for variable name, in fact that code sample is impossible:

```
ubuntu@devbox:~$ python2
Python 2.7.12 (default, Apr 15 2020, 17:07:12) 
[GCC 5.4.0 20160609] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> pass = "asdf"
  File "<stdin>", line 1
    pass = "asdf"
         ^
SyntaxError: invalid syntax
>>> 
ubuntu@devbox:~$ python3
Python 3.5.2 (default, Apr 16 2020, 17:47:17) 
[GCC 5.4.0 20160609] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> pass = "asdf"
  File "<stdin>", line 1
    pass = "asdf"
         ^
SyntaxError: invalid syntax
```

**Comment by ploxiln** [comment]
(... but if you chose a permissible variable name, the two code samples would be 100% equivalent)

**Comment by ZupoLlask** [comment]
Sorry but that was a problem with the pseudo-code, not with code itself I was using.

I know this is totally weird, that's why I'm asking for help. When I found exactly the same back traces, I decided that maybe it's not just me.

I know both are objects from the same str class, but for some reason the auth process fails when value's attribute is a variable.

Can you please recheck my example forgetting the 'pass' part, as I don't use that? 😅

To be honest, I already tried different variable names for the password (e.g., pw, passw, password, ssd, etc.), and the result is always the same: it won't work if I use it as the value for password attribute, but will work if I write the password itself as the value of that attribute. 

Thanks!

**Comment by ploxiln** [comment]
I tested this script:

```python
from paramiko import SSHClient

host = "192.168.1.99"
username = "limuser"
password = "redacted"
client = SSHClient()
client.load_system_host_keys()
client.connect(host, username=username, password=password)

stdin, stdout, stderr = client.exec_command('pwd')
stdin.close()
print("> %r" % stdout.read(256))
```

(under python-3.7 on macOS) and it worked:

```
$ python minitest.py 
> b'/home/limuser\n'
```

... as expected. python string objects/variables are pretty simple and understandable. your code must be doing something else.

**Comment by ZupoLlask** [comment]
Your are absolutely right... I'm ashamed of my mistake!

Sorry to waste your time.
